POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzE3MjY1NDk5LCJ1c2VySWQiOjF9.wflW4xrz4SjbYpiAT9a0g_4B0xCiYJ5HgzbEzczjEDM

{
    "name": "Test Event 333",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}